# Generated by Django 3.1.4 on 2022-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220218_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='media/profile_pictures/default_profile_picture.png', null=True, upload_to='media/profile_pictures')),
            ],
        ),
    ]
