# Generated by Django 3.1.4 on 2022-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.png', null=True, upload_to='profile_pictures'),
        ),
    ]
