# Generated by Django 4.0.1 on 2022-02-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_userfollows_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
