# Generated by Django 4.0.1 on 2022-02-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_userfollows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
